# Name of this GitHub Actions workflow.
name: "Code Scanning - Action"

on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request:
    branches: ["master", "main"]
  # Scan mainline branches and report all findings: 
  push:
    branches: ["master", "main"]

jobs:
  CodeQL-Build:
    runs-on: ubuntu-latest
    
    permissions:
      security-events: write

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      # Fetch project source with GitHub Actions Checkout.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        # Override language selection by uncommenting this and choosing your languages
        # with:
        #   languages: go, javascript, csharp, python, cpp, java, ruby

      # Autobuild attempts to build any compiled languages (C/C++, C#, Go, or Java).
      # If this step fails, then you should remove it and run the build manually (see below).
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
    
